FROM node:12.7-alpine

WORKDIR /usr/src/app

# install and cache app dependencies
COPY package.json ./
RUN  npm install
RUN  npm install -g @angular/cli @angular-devkit/build-angular ionic

# add app
COPY . .

# start app
EXPOSE 80

CMD ["ng", "serve", "--port", "80", "--host", "0.0.0.0", "--disable-host-check"]
